/**
 * backend/tests/pact/api.provider.pact.test.ts
 *
 * TEST-107 — Pact provider verification for the SorobanPay backend API.
 *
 * This suite reads the pact file generated by the frontend consumer tests and
 * verifies that the backend Express app satisfies every interaction in the contract.
 *
 * How it works:
 *   1. Pact starts the backend Express app on a random port.
 *   2. For each interaction in the pact file, Pact:
 *      a. Calls the provider state setup handler (seeds DB mocks).
 *      b. Replays the recorded request against the running backend.
 *      c. Asserts the response matches the contract.
 *   3. The test fails if any interaction is not satisfied.
 *
 * Run:
 *   cd backend && npx jest tests/pact/api.provider.pact.test.ts --verbose
 *
 * The pact file must exist before running. Generate it by running the consumer
 * tests first:
 *   cd frontend && npx jest tests/pact/api.consumer.pact.test.ts
 *
 * References:
 *   Pact provider verification: https://docs.pact.io/implementation_guides/javascript/docs/provider
 *   Issue TEST-107
 */

import path from 'path';
import { Verifier } from '@pact-foundation/pact';
import express, { Express } from 'express';
import * as http from 'http';

// ─── Module mocks ────────────────────────────────────────────────────────────

/**
 * In-memory DB state — provider state handlers populate this before each
 * interaction so the backend routes return the expected data.
 */
interface MockEvent {
  id: string;
  type: string;
  subscriber: string;
  merchant: string;
  token: string;
  amount: string;
  ledgerTimestamp: bigint;
}

interface MockWebhookEndpoint {
  id: string;
  merchant: string;
  url: string;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
}

let _mockEvents: MockEvent[] = [];
let _mockWebhookEndpoints: MockWebhookEndpoint[] = [];

jest.mock('../src/lib/prisma', () => ({
  __esModule: true,
  default: {
    event: {
      findMany: jest.fn(async (args: {
        where?: Record<string, unknown>;
        orderBy?: unknown;
        take?: number;
        skip?: number;
      }) => {
        let results = [..._mockEvents];
        if (args.where) {
          const { merchant, type, subscriber, token } = args.where as Record<string, unknown>;
          if (merchant) results = results.filter((e) => e.merchant === merchant);
          if (type) results = results.filter((e) => e.type === type);
          if (subscriber) results = results.filter((e) => e.subscriber === subscriber);
          if (token) results = results.filter((e) => e.token === token);
        }
        if (args.skip) results = results.slice(args.skip as number);
        if (args.take) results = results.slice(0, args.take as number);
        return results;
      }),
      findFirst: jest.fn(async (args: { where?: Record<string, unknown> }) => {
        if (!args.where) return null;
        const { merchant, type, subscriber, token } = args.where as Record<string, unknown>;
        return _mockEvents.find(
          (e) =>
            (!merchant || e.merchant === merchant) &&
            (!type || e.type === type) &&
            (!subscriber || e.subscriber === subscriber) &&
            (!token || e.token === token),
        ) ?? null;
      }),
    },
    webhookEndpoint: {
      upsert: jest.fn(async (args: {
        where: unknown;
        update: Record<string, unknown>;
        create: Record<string, unknown>;
      }) => {
        const existing = _mockWebhookEndpoints.find(
          (w) =>
            w.merchant === (args.create as MockWebhookEndpoint).merchant &&
            w.url === (args.create as MockWebhookEndpoint).url,
        );
        if (existing) {
          Object.assign(existing, args.update);
          return existing;
        }
        const record: MockWebhookEndpoint = {
          id: String(_mockWebhookEndpoints.length + 1),
          ...(args.create as Omit<MockWebhookEndpoint, 'id' | 'createdAt' | 'updatedAt'>),
          createdAt: new Date(),
          updatedAt: new Date(),
        };
        _mockWebhookEndpoints.push(record);
        return record;
      }),
    },
  },
}));

// Silence tracing and other noisy side-effects during verification
jest.mock('../src/lib/tracing', () => ({
  initTracing: jest.fn(),
  getTracer: jest.fn(),
  withSpan: jest.fn(async (_t: unknown, _n: unknown, fn: (span: unknown) => Promise<void>) =>
    fn({ setAttributes: jest.fn() }),
  ),
  SpanKind: { CLIENT: 0 },
}));
jest.mock('../src/lib/config', () => ({
  validateConfig: jest.fn(() => ({
    port: 3001,
    rpcUrl: 'http://localhost:8545',
    contractId: 'CTEST',
    databaseUrl: 'mock://db',
  })),
}));
jest.mock('../src/services/subscriptionStateService', () => ({
  getSubscriptionStatus: jest.fn(async () => 'ACTIVE'),
  applyEvent: jest.fn(),
}));

// ─── Build the Express app under test ────────────────────────────────────────

/**
 * Assemble a minimal Express app containing only the routes covered by the
 * consumer contracts. This avoids starting cron jobs, the event indexer, or
 * any other side-effect from the full backend entry point.
 */
function buildTestApp(): Express {
  // Late require so mocks are in place before the modules load
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const subscriptionsRouter = require('../src/routes/subscriptions').default;
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const webhooksRouter = require('../src/routes/webhooks').default;
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { buildHealthRouter } = require('../src/routes/health');

  const app = express();
  app.use(express.json());
  app.use('/api/v1/subscriptions', subscriptionsRouter);
  app.use('/api/v1/webhooks', webhooksRouter);
  app.use('/health', buildHealthRouter('http://localhost:8545', 'CTEST'));
  return app;
}

// ─── Provider state constants (match consumer test state descriptions) ────────

const MERCHANT = 'GMERCHANT0000000000000000000000000000000000000000000001';
const SUBSCRIBER = 'GSUB0000000000000000000000000000000000000000000000001';
const TOKEN = 'CTOK0000000000000000000000000000000000000000000000001';

/** Seed data for "merchant has one active subscription" */
function seedOneSubscription(): void {
  _mockEvents = [
    {
      id: '1',
      type: 'subscribe',
      subscriber: SUBSCRIBER,
      merchant: MERCHANT,
      token: TOKEN,
      amount: '1000000',
      ledgerTimestamp: 100n,
    },
  ];
}

/** Seed data for "merchant has executed payments" */
function seedExecutedPayments(): void {
  _mockEvents = [
    {
      id: '2',
      type: 'executed',
      subscriber: SUBSCRIBER,
      merchant: MERCHANT,
      token: TOKEN,
      amount: '1000000',
      ledgerTimestamp: 200n,
    },
  ];
}

/** Seed data for "merchant has subscriptions for multiple tokens" */
function seedMultiTokenSubscriptions(): void {
  _mockEvents = [
    {
      id: '3',
      type: 'subscribe',
      subscriber: SUBSCRIBER,
      merchant: MERCHANT,
      token: TOKEN,
      amount: '1000000',
      ledgerTimestamp: 300n,
    },
    {
      id: '4',
      type: 'subscribe',
      subscriber: SUBSCRIBER,
      merchant: MERCHANT,
      token: 'COTHER_TOKEN_000000000000000000000000000000000000000001',
      amount: '2000000',
      ledgerTimestamp: 301n,
    },
  ];
}

// ─── Start the app on a random port ──────────────────────────────────────────

let server: http.Server;
let appPort: number;

beforeAll(() =>
  new Promise<void>((resolve) => {
    const app = buildTestApp();
    server = app.listen(0, () => {
      appPort = (server.address() as { port: number }).port;
      resolve();
    });
  }),
);

afterAll(() => new Promise<void>((resolve, reject) =>
  server.close((err) => (err ? reject(err) : resolve())),
));

// ─── Pact provider verification ───────────────────────────────────────────────

describe('Pact provider verification — SorobanPayBackend', () => {
  it('satisfies all interactions in the consumer pact', async () => {
    const opts = {
      provider: 'SorobanPayBackend',
      providerBaseUrl: `http://localhost:${appPort}`,

      // Load pact file from shared /pacts directory at repo root.
      // In CI this file is generated by the consumer job (see ci.yml).
      pactUrls: [
        path.resolve(
          __dirname,
          '../../../pacts/SorobanPayFrontend-SorobanPayBackend.json',
        ),
      ],

      // Provider state handlers: called before each interaction to seed the
      // correct DB state. The description strings must match exactly what the
      // consumer tests define in `states: [{ description: '...' }]`.
      stateHandlers: {
        'merchant has one active subscription': async () => {
          _mockEvents = [];
          _mockWebhookEndpoints = [];
          seedOneSubscription();
        },
        'merchant has no subscriptions': async () => {
          _mockEvents = [];
          _mockWebhookEndpoints = [];
        },
        'merchant has executed payments': async () => {
          _mockEvents = [];
          _mockWebhookEndpoints = [];
          seedExecutedPayments();
        },
        'merchant has subscriptions for multiple tokens': async () => {
          _mockEvents = [];
          _mockWebhookEndpoints = [];
          seedMultiTokenSubscriptions();
        },
        'no webhook exists for this merchant/url pair': async () => {
          _mockEvents = [];
          _mockWebhookEndpoints = [];
        },
        'backend is running': async () => {
          _mockEvents = [];
          _mockWebhookEndpoints = [];
        },
        'backend is healthy': async () => {
          // Health endpoint does not need DB state
        },
      },

      logLevel: 'warn',
      // Fail the test if the pact file does not exist (consumer must run first)
      failIfNoPactsFound: true,
    };

    await new Verifier(opts).verifyProvider();
  }, 30_000);
});
